/* USER EVENT */
export const FETCH_USER_DATA_REQUEST = 'FETCH_USER_DATA_REQUEST'
export const FETCH_USER_DATA_SUCCESS = 'FETCH_USER_DATA_SUCCESS'
export const FETCH_USER_DATA_ERROR = 'FETCH_USER_DATA_ERROR'
/* CATEGORY EVENT */
export const ID_PASSING = 'ID_PASSING'
/* ADV. FIELD EVENT */
export const ADV_FIELD = 'ADV_FIELD'
/* RANDOM EVENT */
export const RANDOM_NUMBER = 'RANDOM_NUMBER'
/* FILTER MAP */
export const FILTER_MAP = 'FILTER_MAP'
/* SORT DESIGNS */
export const SORT_DESIGNS = 'SORT_DESIGNS'
/* FILTER DESIGNS*/
export const FILTER_DESIGNS = 'FILTER_DESIGNS'

export const SAVE_CATEGORY_DATA = 'SAVE_CATEGORY_DATA'